/// Flutter icons MyApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyApp
///      fonts:
///       - asset: fonts/MyApp.ttf
///
/// 
///

// Flutter imports:
import 'package:flutter/widgets.dart';

/// This is an autogenerate file by FlutterIcon.com and this has the objetive of include
/// The Visa and MasterCard icons to the project.

class MyApp {
  MyApp._();

  static const _kFontFam = 'MyApp';
  static const String? _kFontPkg = null;

  static const IconData visa = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData master_mastercard = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
